# https://docs.armbian.com/Developer-Guide_Build-Switches/ 
BOARD=pocketchip 
BRANCH=current 
BUILD_DESKTOP=yes 
BUILD_MINIMAL=no 
DESKTOP_ENVIRONMENT=xfce
DESKTOP_TIER=minimal
KERNEL_CONFIGURE=no 
RELEASE=trixie 
DISABLE_KERNEL_PATCHES=yes
DEBUG=yes
ENABLE_EXTENSIONS=preset-firstrun
CONSOLE_AUTOLOGIN=yes
# INSTALL_HEADERS=yes
