BOARD=pocketchip-sd 
BRANCH=current 
BUILD_DESKTOP=no 
BUILD_MINIMAL=yes 
DESKTOP_APPGROUPS_SELECTED=''
KERNEL_CONFIGURE=no 
RELEASE=trixie 
DISABLE_KERNEL_PATCHES=yes
DEBUG=yes
ENABLE_EXTENSIONS=preset-firstrun
# INSTALL_HEADERS=yes
