name: Build PocketCHIP Armbian Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu-24.04-arm, ubuntu-24.04-riscv
    steps:
      - name: Set current date
        id: date
        run: echo "today=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT
        
      - uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.BUILD_TOKEN }}
          armbian_board: "pocketchip-sd" 
          armbian_release: "noble" # trixie
          armbian_target: "build pocketchip"
          armbian_ui: "minimal" # server xfce
          armbian_runner_clean: "yes" # recommended for Github runners
          armbian_release_title: ${{ steps.date.outputs.today }}
          
